-- MySQL Script generated by MySQL Workbench
-- 11/29/15 15:24:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema convo_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema convo_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `convo_db` DEFAULT CHARACTER SET utf8 ;
USE `convo_db` ;

-- -----------------------------------------------------
-- Table `convo_db`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `convo_db`.`Users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `convo_db`.`Threads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `convo_db`.`Threads` (
  `thread_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(140) NOT NULL,
  `created_at` FLOAT NOT NULL,
  PRIMARY KEY (`thread_id`),
  UNIQUE INDEX `thread_id_UNIQUE` (`thread_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `convo_db`.`Convos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `convo_db`.`Convos` (
  `convo_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sender_id` INT NOT NULL,
  `thread_id` INT UNSIGNED NOT NULL,
  `body` VARCHAR(64000) NOT NULL,
  `parent_convo_id` INT UNSIGNED NULL,
  `created_at` FLOAT NOT NULL,
  PRIMARY KEY (`convo_id`),
  UNIQUE INDEX `message_id_UNIQUE` (`convo_id` ASC),
  INDEX `fk_Convos_Convos_idx` (`parent_convo_id` ASC),
  INDEX `fk_Messages_Threads_idx` (`thread_id` ASC),
  INDEX `fk_Messages_Users_idx` (`sender_id` ASC),
  CONSTRAINT `fk_Messages_Messages`
    FOREIGN KEY (`parent_convo_id`)
    REFERENCES `convo_db`.`Convos` (`convo_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Messages_Threads`
    FOREIGN KEY (`thread_id`)
    REFERENCES `convo_db`.`Threads` (`thread_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Messages_Users`
    FOREIGN KEY (`sender_id`)
    REFERENCES `convo_db`.`Users` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `convo_db`.`Receipts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `convo_db`.`Receipts` (
  `receipt_id` INT UNSIGNED NOT NULL,
  `recipient_id` INT NOT NULL,
  `convo_id` INT NOT NULL,
  `read` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` FLOAT NOT NULL,
  `modified_at` FLOAT NOT NULL,
  PRIMARY KEY (`receipt_id`),
  UNIQUE INDEX `receipts_id_UNIQUE` (`receipt_id` ASC),
  INDEX `fk_Receipts_Users_idx` (`recipient_id` ASC),
  INDEX `fk_Receipts_Convos_idx` (`convo_id` ASC),
  CONSTRAINT `fk_Receipts_Users`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `convo_db`.`Users` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receipts_Convos`
    FOREIGN KEY (`convo_id`)
    REFERENCES `convo_db`.`Convos` (`convo_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
